import { describe, expect, it } from 'vitest'
import {
  MAX_REQUEST_BINS,
  validateApprove,
  validateCardRequestInput,
  validateReject,
} from '../src/modules/cardRequests/validate'
import type { NetworkForValidation } from '../src/modules/networks/queries'

/**
 * The request validators, with no Worker and no database -- the same shape as
 * binRules.test.ts and handleValidate.test.ts.
 *
 * The HTTP file next door proves these are wired up. This one proves they say
 * the right thing, which is a different question: the accumulator style only
 * earns its keep if a body with four faults comes back with four sentences
 * rather than the first one.
 */

const NETWORKS: NetworkForValidation[] = [
  { id: 'network_a', code: 'visa', isActive: true, binRules: [{ kind: 'glob', value: '4*' }] },
  { id: 'network_b', code: 'rupay', isActive: true, binRules: [{ kind: 'glob', value: '6[05]*' }] },
  { id: 'network_c', code: 'retired', isActive: false, binRules: [{ kind: 'glob', value: '9*' }] },
]

function card(extra: Record<string, unknown> = {}) {
  return { kind: 'card', issuer: 'Some Bank', cardName: 'Some Card', network: 'visa', ...extra }
}

function errorsFor(body: unknown): string[] {
  const result = validateCardRequestInput(body, NETWORKS)
  return result.ok ? [] : result.errors
}

describe('validateCardRequestInput', () => {
  it('accepts a whole card request', () => {
    const result = validateCardRequestInput(card({ bins: ['411111'], note: 'Mine.' }), NETWORKS)

    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.value).toMatchObject({
      kind: 'card',
      issuer: 'Some Bank',
      cardName: 'Some Card',
      network: 'visa',
      bins: ['411111'],
      note: 'Mine.',
    })
  })

  it('reports every fault at once rather than the first', () => {
    const errors = errorsFor({ kind: 'card', network: 'nope', bins: ['12345'], note: '' })

    // Unknown network, missing issuer, missing card name, malformed prefix.
    expect(errors.length).toBeGreaterThanOrEqual(4)
  })

  it('cannot judge a body whose kind it does not recognise', () => {
    expect(errorsFor({ kind: 'wallet', network: 'visa' })).toEqual([
      "kind must be 'card' or 'bin'.",
    ])
  })

  it('refuses an id the server would have minted', () => {
    expect(errorsFor(card({ id: 'creq_' + '0'.repeat(32) }))).toContainEqual(
      expect.stringContaining('generated by the server'),
    )
  })

  it('rejects a network we do not carry, and one we retired', () => {
    expect(errorsFor(card({ network: 'nope' }))).toContainEqual(
      expect.stringContaining("'nope' is not a network we carry"),
    )
    expect(errorsFor(card({ network: 'retired' }))).toContainEqual(
      expect.stringContaining("'retired' is not a network we carry"),
    )
  })

  describe('BIN prefixes', () => {
    it('takes 6 and 8 digits and nothing between', () => {
      expect(errorsFor(card({ bins: ['411111', '41111111'] }))).toEqual([])
      expect(errorsFor(card({ bins: ['4111111'] }))).toContainEqual(
        expect.stringContaining('must be 6 or 8 digits'),
      )
    })

    it('checks the prefix against the network it was filed under', () => {
      expect(errorsFor(card({ network: 'rupay', bins: ['411111'] }))).toContainEqual(
        "BIN '411111' is not valid for network 'rupay'.",
      )
    })

    it('names a full card number for what it is, and does not repeat it back', () => {
      const pan = '4111111111111111'
      const errors = errorsFor(card({ bins: [pan] }))

      expect(errors.join(' ')).toMatch(/never enter your full card number/i)
      expect(errors.join(' ')).not.toContain(pan)
    })

    it('keeps one copy of a prefix listed twice', () => {
      const result = validateCardRequestInput(card({ bins: ['411111', '411111'] }), NETWORKS)
      expect(result.ok && result.value.bins).toEqual(['411111'])
    })

    it('caps how many one request may carry', () => {
      const bins = Array.from({ length: MAX_REQUEST_BINS + 1 }, (_, i) => `41${String(i).padStart(4, '0')}`)
      expect(errorsFor(card({ bins }))).toContainEqual(expect.stringContaining('at most'))
    })

    it('does not pile a per-prefix complaint on top of an unknown network', () => {
      const errors = errorsFor(card({ network: 'nope', bins: ['411111', '411112'] }))
      expect(errors.filter((e) => e.startsWith('BIN '))).toEqual([])
    })
  })

  describe('telling the two kinds apart', () => {
    it("wants a card id on a 'bin' request", () => {
      expect(errorsFor({ kind: 'bin', network: 'visa' })).toContainEqual(
        expect.stringContaining('cardId'),
      )
    })

    it("refuses a 'bin' request that also describes a new card", () => {
      const errors = errorsFor({
        kind: 'bin',
        cardId: 'card_' + '0'.repeat(32),
        network: 'visa',
        cardName: 'Smuggled',
        issuer: 'Smuggled Bank',
      })

      expect(errors).toHaveLength(2)
      expect(errors.join(' ')).toMatch(/does not belong/)
    })

    it("refuses a 'card' request that names an existing card", () => {
      expect(errorsFor(card({ cardId: 'card_' + '0'.repeat(32) }))).toContainEqual(
        expect.stringContaining('does not exist yet'),
      )
    })
  })

  it('bounds the note', () => {
    expect(errorsFor(card({ note: 'x'.repeat(281) }))).toContainEqual(
      expect.stringContaining('between 1 and 280'),
    )
  })
})

describe('validateApprove', () => {
  it('takes an empty body, which is the whole of a BIN approval', () => {
    expect(validateApprove({})).toEqual({ ok: true, value: { cardId: undefined, note: undefined } })
  })

  it('rejects a card id that is not one', () => {
    expect(validateApprove({ cardId: 'nope' })).toMatchObject({ ok: false })
  })
})

describe('validateReject', () => {
  it('insists on a reason', () => {
    expect(validateReject({})).toEqual({ ok: false, errors: ['A rejection must say why.'] })
  })

  it('takes one', () => {
    expect(validateReject({ note: 'Duplicate of an existing card.' })).toEqual({
      ok: true,
      value: { note: 'Duplicate of an existing card.' },
    })
  })
})
