import { describe, expect, it } from 'vitest'
import { generateId, idPattern } from '../src/http/ids'
import { likePattern, parseIds, parseLimit, parseOffset } from '../src/http/params'
import { BANK_ID_PATTERN, generateBankId } from '../src/modules/banks/bankTypes'
import { validateBankInput, validateBankPatch } from '../src/modules/banks/validate'
import { CARD_ID_PATTERN, generateCardId } from '../src/modules/cards/cardTypes'
import { validateCardInput, validateCardPatch } from '../src/modules/cards/validate'
import type { NetworkForValidation } from '../src/modules/networks/queries'

const bankId = generateBankId()
const valid = { bankId, name: 'Test Card', country: 'IN' }

/**
 * Stands in for what listNetworksForValidation returns. Includes an inactive
 * and a ruleless network, because those are distinct rejections.
 */
const NETWORKS: NetworkForValidation[] = [
  { id: 'network_'.padEnd(40, 'a'), code: 'visa', isActive: true, binRules: [{ kind: 'glob', value: '4*' }] },
  { id: 'network_'.padEnd(40, 'b'), code: 'rupay', isActive: true, binRules: [{ kind: 'glob', value: '6[05]*' }] },
  { id: 'network_'.padEnd(40, 'c'), code: 'retired', isActive: false, binRules: [{ kind: 'glob', value: '9*' }] },
  { id: 'network_'.padEnd(40, 'd'), code: 'ruleless', isActive: true, binRules: [] },
]

describe('id generation', () => {
  it('produces prefixed ids of the documented shape', () => {
    expect(generateCardId()).toMatch(CARD_ID_PATTERN)
    expect(generateBankId()).toMatch(BANK_ID_PATTERN)
    expect(generateCardId()).toHaveLength(37)
    expect(generateBankId()).toHaveLength(37)
  })

  it('keeps the prefixes distinct', () => {
    expect(CARD_ID_PATTERN.test(generateBankId())).toBe(false)
    expect(BANK_ID_PATTERN.test(generateCardId())).toBe(false)
  })

  it('does not repeat', () => {
    const ids = new Set(Array.from({ length: 1000 }, () => generateCardId()))
    expect(ids.size).toBe(1000)
  })

  it('builds a pattern that rejects a wrong-length body', () => {
    expect(idPattern('card').test('card_abc')).toBe(false)
    expect(idPattern('card').test(generateId('card'))).toBe(true)
  })
})

describe('likePattern', () => {
  it('escapes both wildcards and the escape character itself', () => {
    expect(likePattern('50%_off')).toBe('%50\\%\\_off%')
    expect(likePattern('back\\slash')).toBe('%back\\\\slash%')
  })

  it('leaves ordinary text alone', () => {
    expect(likePattern('axis')).toBe('%axis%')
  })
})

describe('query params', () => {
  it('falls back to defaults on junk', () => {
    expect(parseLimit('abc')).toBe(50)
    expect(parseLimit('0')).toBe(50)
    expect(parseLimit('9999')).toBe(100)
    expect(parseOffset('-4')).toBe(0)
  })

  it('trims, drops blanks, and de-duplicates ids', () => {
    expect(parseIds('a,,b, a ')).toEqual(['a', 'b'])
    expect(parseIds(undefined)).toBeUndefined()
    expect(parseIds('')).toEqual([])
  })

  it('caps ids to stay under the D1 bound-parameter limit', () => {
    const many = Array.from({ length: 200 }, (_, i) => `c${i}`).join(',')
    expect(parseIds(many)).toHaveLength(50)
  })
})

describe('validateCardInput', () => {
  it('accepts a well-formed card', () => {
    expect(validateCardInput(valid, NETWORKS).ok).toBe(true)
  })

  it('requires a syntactically valid bankId', () => {
    expect(validateCardInput({ ...valid, bankId: 'not-an-id' }, NETWORKS).ok).toBe(false)
    expect(validateCardInput({ ...valid, bankId: generateCardId() }, NETWORKS).ok).toBe(false)
    expect(validateCardInput({ name: 'x', country: 'IN' }, NETWORKS).ok).toBe(false)
  })

  it('refuses a client-supplied id', () => {
    const result = validateCardInput({ ...valid, id: 'card_mine' }, NETWORKS)
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.errors[0]).toContain('generated by the server')
  })

  it('reports every problem at once rather than the first', () => {
    const result = validateCardInput({ bankId: 'bad', name: '', country: 'nope' }, NETWORKS)
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.errors).toHaveLength(3)
  })

  it('normalises country case', () => {
    const result = validateCardInput({ ...valid, country: 'in' }, NETWORKS)
    expect(result.ok && result.value.country).toBe('IN')
  })

  it('trims surrounding whitespace', () => {
    const result = validateCardInput({ ...valid, name: '  Infinia  ' }, NETWORKS)
    expect(result.ok && result.value.name).toBe('Infinia')
  })

  it('rejects control characters in free text', () => {
    expect(validateCardInput({ ...valid, name: 'BadName' }, NETWORKS).ok).toBe(false)
    expect(validateCardInput({ ...valid, name: 'Two\nLines' }, NETWORKS).ok).toBe(false)
  })

  it('rejects a non-string name', () => {
    expect(validateCardInput({ ...valid, name: 42 }, NETWORKS).ok).toBe(false)
  })

  it('rejects a non-boolean isActive', () => {
    expect(validateCardInput({ ...valid, isActive: 'true' }, NETWORKS).ok).toBe(false)
  })

  it('defaults omitted fees to zero', () => {
    const result = validateCardInput(valid, NETWORKS)
    expect(result.ok && result.value.joiningFee).toBe(0)
    expect(result.ok && result.value.annualFee).toBe(0)
  })

  it('accepts the largest published fee in the catalog', () => {
    expect(
      validateCardInput({ ...valid, joiningFee: 700000, annualFee: 275000 }, NETWORKS).ok,
    ).toBe(true)
  })

  it('rejects a fee that is negative, fractional, or a string', () => {
    expect(validateCardInput({ ...valid, annualFee: -1 }, NETWORKS).ok).toBe(false)
    expect(validateCardInput({ ...valid, annualFee: 12.5 }, NETWORKS).ok).toBe(false)
    expect(validateCardInput({ ...valid, annualFee: '5000' }, NETWORKS).ok).toBe(false)
  })
})

describe('validateCardPatch', () => {
  it('rejects an empty patch', () => {
    expect(validateCardPatch({}, NETWORKS).ok).toBe(false)
  })

  it('accepts a single field', () => {
    const result = validateCardPatch({ name: 'Infinia' }, NETWORKS)
    expect(result.ok && result.value).toEqual({ name: 'Infinia' })
  })

  it('validates bankId when moving a card', () => {
    expect(validateCardPatch({ bankId: 'nope' }, NETWORKS).ok).toBe(false)
    expect(validateCardPatch({ bankId }, NETWORKS).ok).toBe(true)
  })

  it('refuses a client-supplied id', () => {
    expect(validateCardPatch({ id: 'card_mine', name: 'x' }, NETWORKS).ok).toBe(false)
  })
})

describe('validateBankInput', () => {
  it('accepts a well-formed bank', () => {
    expect(validateBankInput({ name: 'HDFC Bank' }).ok).toBe(true)
  })

  it('requires a name', () => {
    expect(validateBankInput({}).ok).toBe(false)
    expect(validateBankInput({ name: '   ' }).ok).toBe(false)
  })

  it('refuses a client-supplied id', () => {
    expect(validateBankInput({ id: 'bank_mine', name: 'HDFC Bank' }).ok).toBe(false)
  })

  it('rejects a name longer than the column allows', () => {
    expect(validateBankInput({ name: 'a'.repeat(81) }).ok).toBe(false)
  })
})

describe('validateBankPatch', () => {
  it('rejects an empty patch', () => {
    expect(validateBankPatch({}).ok).toBe(false)
  })

  it('accepts a rename', () => {
    const result = validateBankPatch({ name: 'Axis Bank' })
    expect(result.ok && result.value).toEqual({ name: 'Axis Bank' })
  })
})

describe('validateCardInput networks', () => {
  const card = (networks: unknown) => ({
    bankId: 'bank_'.padEnd(37, 'a'),
    name: 'Test',
    country: 'IN',
    networks,
  })

  const errorsFor = (networks: unknown): string[] => {
    const result = validateCardInput(card(networks), NETWORKS)
    return result.ok ? [] : result.errors
  }

  it('accepts a network with a matching bin', () => {
    const result = validateCardInput(card([{ code: 'visa', bins: ['412345'] }]), NETWORKS)
    expect(result.ok).toBe(true)
    if (result.ok) expect(result.value.networks).toEqual([{ code: 'visa', bins: ['412345'] }])
  })

  it('accepts an empty networks array as "on no networks"', () => {
    const result = validateCardInput(card([]), NETWORKS)
    expect(result.ok).toBe(true)
    if (result.ok) expect(result.value.networks).toEqual([])
  })

  it('defaults a missing bins list to empty', () => {
    const result = validateCardInput(card([{ code: 'visa' }]), NETWORKS)
    expect(result.ok).toBe(true)
    if (result.ok) expect(result.value.networks).toEqual([{ code: 'visa', bins: [] }])
  })

  it('normalises a code to lowercase', () => {
    const result = validateCardInput(card([{ code: 'VISA', bins: [] }]), NETWORKS)
    expect(result.ok).toBe(true)
    if (result.ok) expect(result.value.networks).toEqual([{ code: 'visa', bins: [] }])
  })

  it('de-duplicates a repeated bin within one network', () => {
    const result = validateCardInput(
      card([{ code: 'visa', bins: ['412345', '412345'] }]),
      NETWORKS,
    )
    expect(result.ok).toBe(true)
    if (result.ok) expect(result.value.networks).toEqual([{ code: 'visa', bins: ['412345'] }])
  })

  it('reports an unknown code', () => {
    expect(errorsFor([{ code: 'switch' }]).join(' ')).toMatch(/'switch' is not a known network/)
  })

  it('reports an inactive network', () => {
    expect(errorsFor([{ code: 'retired' }]).join(' ')).toMatch(/'retired' is not active/)
  })

  it('reports a network with no rules once bins are given', () => {
    expect(errorsFor([{ code: 'ruleless', bins: ['912345'] }]).join(' ')).toMatch(
      /has no BIN rules on file/,
    )
  })

  it('allows a ruleless network with no bins', () => {
    expect(validateCardInput(card([{ code: 'ruleless' }]), NETWORKS).ok).toBe(true)
  })

  it('reports a bin that fails its network rules', () => {
    expect(errorsFor([{ code: 'visa', bins: ['512345'] }]).join(' ')).toMatch(
      /BIN '512345' is not valid for network 'visa'/,
    )
  })

  it('reports a bin of the wrong length', () => {
    expect(errorsFor([{ code: 'visa', bins: ['4123'] }]).join(' ')).toMatch(/6 or 8 digits/)
  })

  it('reports a repeated network', () => {
    expect(errorsFor([{ code: 'visa' }, { code: 'visa' }]).join(' ')).toMatch(/listed twice/)
  })

  it('reports one bin claimed by two networks', () => {
    expect(
      errorsFor([
        { code: 'visa', bins: ['412345'] },
        { code: 'rupay', bins: ['412345'] },
      ]).join(' '),
    ).toMatch(/more than one network/)
  })

  it('reports a non-object network entry', () => {
    expect(errorsFor(['visa']).join(' ')).toMatch(/must be an object/)
  })

  it('reports a non-array networks field', () => {
    expect(errorsFor('visa').join(' ')).toMatch(/networks must be an array/)
  })
})
