import { describe, expect, it } from 'vitest'
import { generateId, idPattern } from '../src/http/ids'
import { likePattern, parseIds, parseLimit, parseOffset } from '../src/http/params'
import { BANK_ID_PATTERN, generateBankId } from '../src/modules/banks/bankTypes'
import { validateBankInput, validateBankPatch } from '../src/modules/banks/validate'
import { CARD_ID_PATTERN, generateCardId } from '../src/modules/cards/cardTypes'
import { validateCardInput, validateCardPatch } from '../src/modules/cards/validate'

const bankId = generateBankId()
const valid = { bankId, name: 'Test Card', country: 'IN' }

describe('id generation', () => {
  it('produces prefixed ids of the documented shape', () => {
    expect(generateCardId()).toMatch(CARD_ID_PATTERN)
    expect(generateBankId()).toMatch(BANK_ID_PATTERN)
    expect(generateCardId()).toHaveLength(37)
    expect(generateBankId()).toHaveLength(37)
  })

  it('keeps the prefixes distinct', () => {
    expect(CARD_ID_PATTERN.test(generateBankId())).toBe(false)
    expect(BANK_ID_PATTERN.test(generateCardId())).toBe(false)
  })

  it('does not repeat', () => {
    const ids = new Set(Array.from({ length: 1000 }, () => generateCardId()))
    expect(ids.size).toBe(1000)
  })

  it('builds a pattern that rejects a wrong-length body', () => {
    expect(idPattern('card').test('card_abc')).toBe(false)
    expect(idPattern('card').test(generateId('card'))).toBe(true)
  })
})

describe('likePattern', () => {
  it('escapes both wildcards and the escape character itself', () => {
    expect(likePattern('50%_off')).toBe('%50\\%\\_off%')
    expect(likePattern('back\\slash')).toBe('%back\\\\slash%')
  })

  it('leaves ordinary text alone', () => {
    expect(likePattern('axis')).toBe('%axis%')
  })
})

describe('query params', () => {
  it('falls back to defaults on junk', () => {
    expect(parseLimit('abc')).toBe(50)
    expect(parseLimit('0')).toBe(50)
    expect(parseLimit('9999')).toBe(100)
    expect(parseOffset('-4')).toBe(0)
  })

  it('trims, drops blanks, and de-duplicates ids', () => {
    expect(parseIds('a,,b, a ')).toEqual(['a', 'b'])
    expect(parseIds(undefined)).toBeUndefined()
    expect(parseIds('')).toEqual([])
  })

  it('caps ids to stay under the D1 bound-parameter limit', () => {
    const many = Array.from({ length: 200 }, (_, i) => `c${i}`).join(',')
    expect(parseIds(many)).toHaveLength(50)
  })
})

describe('validateCardInput', () => {
  it('accepts a well-formed card', () => {
    expect(validateCardInput(valid).ok).toBe(true)
  })

  it('requires a syntactically valid bankId', () => {
    expect(validateCardInput({ ...valid, bankId: 'not-an-id' }).ok).toBe(false)
    expect(validateCardInput({ ...valid, bankId: generateCardId() }).ok).toBe(false)
    expect(validateCardInput({ name: 'x', country: 'IN' }).ok).toBe(false)
  })

  it('refuses a client-supplied id', () => {
    const result = validateCardInput({ ...valid, id: 'card_mine' })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.errors[0]).toContain('generated by the server')
  })

  it('reports every problem at once rather than the first', () => {
    const result = validateCardInput({ bankId: 'bad', name: '', country: 'nope' })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.errors).toHaveLength(3)
  })

  it('normalises country case', () => {
    const result = validateCardInput({ ...valid, country: 'in' })
    expect(result.ok && result.value.country).toBe('IN')
  })

  it('trims surrounding whitespace', () => {
    const result = validateCardInput({ ...valid, name: '  Infinia  ' })
    expect(result.ok && result.value.name).toBe('Infinia')
  })

  it('rejects control characters in free text', () => {
    expect(validateCardInput({ ...valid, name: 'BadName' }).ok).toBe(false)
    expect(validateCardInput({ ...valid, name: 'Two\nLines' }).ok).toBe(false)
  })

  it('rejects a non-string name', () => {
    expect(validateCardInput({ ...valid, name: 42 }).ok).toBe(false)
  })

  it('rejects a non-boolean isActive', () => {
    expect(validateCardInput({ ...valid, isActive: 'true' }).ok).toBe(false)
  })

  it('defaults omitted fees to zero', () => {
    const result = validateCardInput(valid)
    expect(result.ok && result.value.joiningFee).toBe(0)
    expect(result.ok && result.value.annualFee).toBe(0)
  })

  it('accepts the largest published fee in the catalog', () => {
    expect(validateCardInput({ ...valid, joiningFee: 700000, annualFee: 275000 }).ok).toBe(true)
  })

  it('rejects a fee that is negative, fractional, or a string', () => {
    expect(validateCardInput({ ...valid, annualFee: -1 }).ok).toBe(false)
    expect(validateCardInput({ ...valid, annualFee: 12.5 }).ok).toBe(false)
    expect(validateCardInput({ ...valid, annualFee: '5000' }).ok).toBe(false)
  })
})

describe('validateCardPatch', () => {
  it('rejects an empty patch', () => {
    expect(validateCardPatch({}).ok).toBe(false)
  })

  it('accepts a single field', () => {
    const result = validateCardPatch({ name: 'Infinia' })
    expect(result.ok && result.value).toEqual({ name: 'Infinia' })
  })

  it('validates bankId when moving a card', () => {
    expect(validateCardPatch({ bankId: 'nope' }).ok).toBe(false)
    expect(validateCardPatch({ bankId }).ok).toBe(true)
  })

  it('refuses a client-supplied id', () => {
    expect(validateCardPatch({ id: 'card_mine', name: 'x' }).ok).toBe(false)
  })
})

describe('validateBankInput', () => {
  it('accepts a well-formed bank', () => {
    expect(validateBankInput({ name: 'HDFC Bank' }).ok).toBe(true)
  })

  it('requires a name', () => {
    expect(validateBankInput({}).ok).toBe(false)
    expect(validateBankInput({ name: '   ' }).ok).toBe(false)
  })

  it('refuses a client-supplied id', () => {
    expect(validateBankInput({ id: 'bank_mine', name: 'HDFC Bank' }).ok).toBe(false)
  })

  it('rejects a name longer than the column allows', () => {
    expect(validateBankInput({ name: 'a'.repeat(81) }).ok).toBe(false)
  })
})

describe('validateBankPatch', () => {
  it('rejects an empty patch', () => {
    expect(validateBankPatch({}).ok).toBe(false)
  })

  it('accepts a rename', () => {
    const result = validateBankPatch({ name: 'Axis Bank' })
    expect(result.ok && result.value).toEqual({ name: 'Axis Bank' })
  })
})
