/**
 * Domain-free validation primitives shared by every module. Anything that knows
 * what a card or a bank *is* belongs in that module's validate.ts instead.
 *
 * The accumulator style is deliberate, and follows the shape
 * frontend/src/data/handles.ts already established: collect every problem, then
 * report them together, so one request does not need four round trips to get
 * clean.
 *
 * These overlap the CHECK constraints in the migrations on purpose. The
 * validators exist to produce a good 400; the constraints are the backstop that
 * no path -- a later module, a stray `wrangler d1 execute` -- can write a bad
 * row. Change one, change the other.
 */

export const COUNTRY_PATTERN = /^[A-Z]{2}$/

/** Rejects control characters so a name cannot smuggle a newline into a log. */
const CONTROL_CHARS = /[\u0000-\u001f\u007f-\u009f]/

export type Fields = Record<string, unknown>

export function isPlainObject(value: unknown): value is Fields {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

export function checkText(
  value: unknown,
  field: string,
  max: number,
  errors: string[],
): string | undefined {
  if (typeof value !== 'string') {
    errors.push(`${field} must be a string.`)
    return undefined
  }
  const trimmed = value.trim()
  if (trimmed.length < 1 || trimmed.length > max) {
    errors.push(`${field} must be between 1 and ${max} characters.`)
    return undefined
  }
  if (CONTROL_CHARS.test(trimmed)) {
    errors.push(`${field} must not contain control characters.`)
    return undefined
  }
  return trimmed
}

export function checkCountry(value: unknown, errors: string[]): string | undefined {
  const raw = typeof value === 'string' ? value.trim().toUpperCase() : ''
  if (!COUNTRY_PATTERN.test(raw)) {
    // Shape only -- 'ZZ' passes. Real ISO 3166-1 membership needs a table.
    errors.push('country must be a two-letter ISO 3166-1 alpha-2 code, e.g. "IN".')
    return undefined
  }
  return raw
}

export function checkInteger(
  value: unknown,
  field: string,
  min: number,
  max: number,
  errors: string[],
): number | undefined {
  if (typeof value !== 'number' || !Number.isInteger(value) || value < min || value > max) {
    errors.push(`${field} must be an integer between ${min} and ${max}.`)
    return undefined
  }
  return value
}

export function checkId(
  value: unknown,
  field: string,
  pattern: RegExp,
  errors: string[],
): string | undefined {
  if (typeof value !== 'string' || !pattern.test(value)) {
    errors.push(`${field} must be a valid id.`)
    return undefined
  }
  return value
}

/** Ids are minted by the server, so a client sending one is a misunderstanding. */
export function rejectClientId(body: Fields, errors: string[]): void {
  if (body.id !== undefined) {
    errors.push('id is generated by the server and must not be supplied.')
  }
}
