-- Migration number: 0005 	 2026-08-29T00:00:00.000Z
-- The launch catalog: 12 issuers and 100 cards, with published fees in
-- whole rupees. Fees change; correct them over the admin API rather than by
-- editing this file, which is applied once and never re-run.
--
-- randomblob(16) yields the same 32 lowercase hex characters generateId()
-- produces, so seeded rows are indistinguishable from API-created ones.

INSERT INTO banks (id, name) VALUES
  ('bank_' || lower(hex(randomblob(16))), 'HDFC'),
  ('bank_' || lower(hex(randomblob(16))), 'ICICI'),
  ('bank_' || lower(hex(randomblob(16))), 'Axis'),
  ('bank_' || lower(hex(randomblob(16))), 'American Express'),
  ('bank_' || lower(hex(randomblob(16))), 'Kotak'),
  ('bank_' || lower(hex(randomblob(16))), 'SBI'),
  ('bank_' || lower(hex(randomblob(16))), 'IndusInd'),
  ('bank_' || lower(hex(randomblob(16))), 'IDFC FIRST'),
  ('bank_' || lower(hex(randomblob(16))), 'HSBC'),
  ('bank_' || lower(hex(randomblob(16))), 'AU'),
  ('bank_' || lower(hex(randomblob(16))), 'RBL'),
  ('bank_' || lower(hex(randomblob(16))), 'Bank of Baroda');

INSERT INTO cards (id, bank_id, name, country, joining_fee, annual_fee) VALUES
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Infinia Metal'             , 'IN', 12500, 12500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Diners Club Black Metal'   , 'IN', 10000, 10000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'Emeralde Private Metal'    , 'IN', 12499, 12499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Magnus for Burgundy'       , 'IN', 12500, 12500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'American Express'), 'Platinum Charge Card'      , 'IN', 66000, 66000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Reserve'                   , 'IN', 50000, 50000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Kotak'), 'White Reserve'             , 'IN', 12500, 12500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'AURUM'                     , 'IN', 9999, 9999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IndusInd'), 'Pinnacle'                  , 'IN', 10000, 10000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Atlas'                     , 'IN', 5000, 5000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Magnus'                    , 'IN', 12500, 12500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IDFC FIRST'), 'Mayura'                    , 'IN', 5999, 5999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HSBC'), 'Taj'                       , 'IN', 12000, 12000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'Times Black'               , 'IN', 20000, 20000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IndusInd'), 'Pioneer Heritage'          , 'IN', 100000, 25000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IndusInd'), 'Pioneer Legacy'            , 'IN', 50000, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IndusInd'), 'Solitaire'                 , 'IN', 30000, 10000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IndusInd'), 'Indulge'                   , 'IN', 75000, 10000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IndusInd'), 'Crest'                     , 'IN', 75000, 10000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HSBC'), 'Privé'                     , 'IN', 275000, 275000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'American Express'), 'Centurion Charge Card'     , 'IN', 700000, 275000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Primus'                    , 'IN', 500000, 300000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'American Express'), 'Platinum Reserve'          , 'IN', 10000, 10000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'American Express'), 'Platinum Travel'           , 'IN', 5000, 5000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Marriott Bonvoy'           , 'IN', 3000, 3000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Regalia Gold'              , 'IN', 2500, 2500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Regalia'                   , 'IN', 2500, 2500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Diners Club Privilege'     , 'IN', 1000, 1000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Diners Club Miles'         , 'IN', 1000, 1000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Millennia'                 , 'IN', 1000, 1000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Swiggy'                    , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Tata Neu Infinity'         , 'IN', 1499, 1499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'Tata Neu Plus'             , 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'PhonePe Ultimo'            , 'IN', 2500, 2500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HDFC'), 'PhonePe Uno'               , 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'Elite'                     , 'IN', 4999, 4999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'Air India Signature'       , 'IN', 4999, 4999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'Air India Platinum'        , 'IN', 1499, 1499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'BPCL Octane'               , 'IN', 1499, 1499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'BPCL'                      , 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'Cashback'                  , 'IN', 999, 999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'SimplyCLICK'               , 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'SimplySAVE'                , 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'IRCTC'                     , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'IRCTC Premier'             , 'IN', 1499, 1499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'Miles ELITE'               , 'IN', 4999, 4999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'Miles'                     , 'IN', 1499, 1499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'Miles PRIME'               , 'IN', 2999, 2999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'Tata Neu Infinity'         , 'IN', 1499, 1499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'SBI'), 'Tata Neu Plus'             , 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'Sapphiro'                  , 'IN', 6500, 3500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'Rubyx'                     , 'IN', 3000, 3000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'Coral'                     , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'Amazon Pay'                , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'Adani One Signature'       , 'IN', 750, 750),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'Adani One Platinum'        , 'IN', 750, 750),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'MakeMyTrip'                , 'IN', 999, 999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'HPCL Super Saver'          , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'HPCL Coral'                , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'ICICI'), 'Manchester United Platinum', 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Horizon'                   , 'IN', 3000, 3000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Select'                    , 'IN', 3000, 3000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Privilege'                 , 'IN', 1500, 1500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Airtel'                    , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Flipkart'                  , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'ACE'                       , 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'IndianOil'                 , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'IndiGo Premium'            , 'IN', 5000, 5000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'IndiGo'                    , 'IN', 2500, 2500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Etihad Guest'              , 'IN', 3500, 3500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'Rewards'                   , 'IN', 1000, 1000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Axis'), 'My Zone'                   , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IDFC FIRST'), 'Wealth'                    , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IDFC FIRST'), 'Select'                    , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IDFC FIRST'), 'WOW!'                      , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IDFC FIRST'), 'Classic'                   , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IDFC FIRST'), 'Power+'                    , 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'AU'), 'Zenith+'                   , 'IN', 4999, 4999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'AU'), 'Zenith'                    , 'IN', 7999, 7999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'AU'), 'Vetta'                     , 'IN', 2999, 2999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'AU'), 'ixigo'                     , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'AU'), 'LIT'                       , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'AU'), 'Altura Plus'               , 'IN', 499, 499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HSBC'), 'Live+'                     , 'IN', 999, 999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HSBC'), 'Premier'                   , 'IN', 20000, 20000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'HSBC'), 'Visa Platinum'             , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IndusInd'), 'Legend'                    , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IndusInd'), 'Tiger'                     , 'IN', 0, 0),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'IndusInd'), 'EazyDiner Signature'       , 'IN', 2999, 2999),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'RBL'), 'World Safari'              , 'IN', 3000, 3000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'RBL'), 'IndianOil XTRA'            , 'IN', 1500, 1500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'RBL'), 'ShopRite'                  , 'IN', 500, 500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'RBL'), 'Platinum Maxima'           , 'IN', 2500, 2500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Bank of Baroda'), 'Eterna'                    , 'IN', 2499, 2499),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Bank of Baroda'), 'Etihad Guest Premium'      , 'IN', 5000, 5000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Bank of Baroda'), 'Premier'                   , 'IN', 1000, 1000),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Kotak'), 'Zen Signature'             , 'IN', 1500, 1500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'Kotak'), 'IndianOil'                 , 'IN', 449, 449),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'American Express'), 'Membership Rewards'        , 'IN', 1000, 4500),
  ('card_' || lower(hex(randomblob(16))), (SELECT id FROM banks WHERE name = 'American Express'), 'Gold Charge'               , 'IN', 1000, 4500);
